AnimeShop/Models/ShopViewModel.cs
using System.Collections.Concurrent;

namespace AnimeShop.Models
{
    public class ShopViewModel
    {
        public List<Category> Categories { get; set; }
        public List<Product> Products { get; set; }
        public List<Product> FavoriteProducts { get; set; }
        public ConcurrentQueue<Product> RecentProducts { get; set; }
        public User User { get; set; }
        public static int CountItemCart { get; set; } = 0;
        public static int CountItemFacourites { get; set; } = 0;

        public string SearchTitle { get; set; }
        public int CategoryID { get; set; }
        public int? minPriceProd { get; set; }
        public int? maxPriceProd { get; set; }
        public int minPrice { get; set; }
        public int maxPrice { get; set; }

        public string Status { get; set; }
    }
}

AnimeShop/Areas/Admin/Controllers/StartController.cs
using AnimeShop.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AnimeShop.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class StartController : Controller
    {
        // GET: StartController
        public ActionResult Start()
        {
            return View();
        }
    }
}

AnimeShop/Controllers/ShopController.cs
using AnimeShop.Models;
using AnimeShop.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace AnimeShop.Controllers
{
    public class ShopController : Controller
    {
        private readonly ShopDBContext context;
        private readonly IShopService shopService;
        private readonly IShopModelService shopModelService;
        private readonly IMailService mailService;

        public ShopController(ShopDBContext context,IShopService shopService,IShopModelService shopModelService,IMailService mailService)
        {
            this.context = context;
            this.shopService = shopService;
            this.shopModelService = shopModelService;
            this.mailService = mailService;
        }
        [HttpGet]
        public async Task<IActionResult> ShopCart(string returnURL)
        {
            var tuple = await shopService.GetUserOrder(HttpContext);
            if(tuple.Item1)
            {
                return View(tuple.Item3);
            }

            TempData["ModelStatus"] = tuple.Item2;

            if (returnURL == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return Redirect(returnURL);
        }


        [HttpPost]
        [ActionName("ShopCart")]
        public IActionResult ConfirmShopCart()
        {
            return View();
        }


        public async Task<IActionResult> AddToCart(int id, string returnURL,int amount = 1)
        {
            var tuple = await shopService.AddProductInCart(HttpContext,id,amount);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }


            if (returnURL == null)
            {
                return RedirectToAction("ShopCart", "Shop");
            }

            return Redirect(returnURL);
        }
        public async Task<IActionResult> AddCountProduct(int id,string returnURL)
        {
            var tuple = await shopService.AddProductInCart(HttpContext, id, 1);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }


            if (returnURL == null)
            {
                return RedirectToAction("ShopCart", "Shop");
            }

            return Redirect(returnURL);
        }

       
        public async Task<IActionResult> RemoveProduct(int id,string returnURL)
        {
            var tuple = await shopService.RemoveProductFromCart(HttpContext, id);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }


            if (returnURL == null)
            {
                return RedirectToAction("ShopCart", "Shop");
            }

            return Redirect(returnURL);
        }
        public async Task<IActionResult> RemoveCountProduct(int id,string returnURL)
        {
            var tuple = await shopService.AddProductInCart(HttpContext, id, -1);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }


            if (returnURL == null)
            {
                return RedirectToAction("ShopCart", "Shop");
            }

            return Redirect(returnURL);
        }



        [HttpGet]
        public async Task<IActionResult> Favourites(string returnURL)
        {
            var tuple = await shopService.GetFavoriteProducts(HttpContext);
            if (tuple.Item1)
            {
                return View(tuple.Item3);
            }

            TempData["ModelStatus"] = tuple.Item2;

            if (returnURL == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return Redirect(returnURL);
        }
        public async Task<IActionResult> AddToFavourites(int id,string returnURL)
        {
            var tuple = await shopService.AddProductInFavourite(HttpContext, id);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }


            if (returnURL == null)
            {
                return RedirectToAction("ShopCart", "Shop");
            }

            return Redirect(returnURL);
        }
        public async Task<IActionResult> RemoveProductFromFeatur(int id)
        {
            var tuple = await shopService.RemoveProductFromFavourite(HttpContext, id);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }
            return RedirectToAction("Favourites", "Shop");
        }



        [HttpGet]
        public async Task<IActionResult> ProductDetail(int id,string returnUrl)
        {
            await shopModelService.AddRecentProduct(HttpContext, id);
            return View(await shopService.GetProductModelById(HttpContext, returnUrl, id));
        }
        [HttpGet]
        public async Task<IActionResult> ShopList(string seacrhTitle, int? CategoryId,int? minPrice,int? maxPrice, bool NeedSearch=true)
        {
            
            ShopViewModel model = await shopModelService.CreateModel(HttpContext);

            model.Categories = context.Categories.ToList();

            if(NeedSearch)
            {
                shopModelService.UpdateProductByParam(seacrhTitle,CategoryId,minPrice,maxPrice,ref model);
            }
            else
            {
                model.SearchTitle = null;
                model.CategoryID = 0;
            }


            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> CheckOut()
        {
            var tuple = await shopService.GetUserOrder(HttpContext);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }
            return View(tuple.Item3);
        }

        [HttpPost]
        public async Task<IActionResult> SendEmail()
        {
            var tuple = await shopService.GetUserOrder(HttpContext);
            if (!tuple.Item1)
            {
                TempData["ModelStatus"] = tuple.Item2;
            }
            else
            {
                await mailService.SendAsync(tuple.Item3,"Order from DWC Shop");
                await shopService.ClearOrder(tuple.Item3.User.Id);
            }
            return RedirectToAction("Index", "Home");
        }


        public async Task<IActionResult> ProductModal(int id)
        {
            Product product;
            product = await shopService.GetProductById(id);


            return PartialView("_CartModelPartial", product);
        }
    }
}

AnimeShop/Views/Shop/CheckOut.cshtml
@{
    ViewData["Title"] = "Checkout";
}
@model Order


<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" asp-action="Index" asp-controller="Home">Home</a>
                <a class="breadcrumb-item text-dark" asp-action="ShopList" asp-controller="Shop">Shop</a>
                <span class="breadcrumb-item active">Checkout</span>
            </nav>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row px-xl-5">
        <form method="post" asp-action="SendEmail" asp-controller="Shop">
            <div class="col-lg-8">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Billing Address</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label>First Name</label>
                            <input required asp-for="User.FirstName" class="form-control" type="text" placeholder="John">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Last Name</label>
                            <input required asp-for="User.SurName" class="form-control" type="text" placeholder="Doe">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>E-mail</label>
                            <input asp-for="User.Email" class="form-control" type="text" placeholder="example@email.com">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Mobile No</label>
                            <input required asp-for="User.Phone" class="form-control" type="text" placeholder="+123 456 789">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Address</label>
                            <input required name="Adress" class="form-control" type="text" placeholder="123 Street">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Order Total</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom">
                        <h6 class="mb-3">Products</h6>
                        @foreach (var item in Model.OrderProducts)
                        {
                            <div class="d-flex justify-content-between">
                                <p>@item.Product.Title</p>
                                <p>₽@item.TotalPrice</p>
                            </div>
                        }
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>₽@Model.totalPrice</h5>
                        </div>
                    </div>
                </div>
                <div class="mb-5">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Payment</span></h5>
                    <div class="bg-light p-30">
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="paypal">
                                <label class="custom-control-label" for="paypal">Paypal</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="directcheck">
                                <label class="custom-control-label" for="directcheck">Direct Check</label>
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                                <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-block btn-primary font-weight-bold py-3">Place Order</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

AnimeShop/Views/Shop/Favourites.cshtml
@{
    ViewData["Title"] = "Favourites cart";
}
@model List<FavoriteProduct>
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" asp-action="Index" asp-controller="Home">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th></th>
                        <th>Price</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="align-middle">@item.Product.Title</td>
                            <td class="align-middle">
                                <div class="product-item">
                                <div class="product-img position-relative overflow-hidden">
                                    <img class="img-fluid w-100" src="@item.Product.ImageURl" alt="">
                                    <div class="product-action">
                                        <a class="btn btn-outline-dark btn-square" asp-route-returnURL="@Context.Request.Path" asp-route-id="@item.Product.Id" asp-action="AddToCart" asp-controller="Shop"><i class="fa fa-shopping-cart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" asp-route-id="@item.Product.Id" asp-route-returnURL="@Context.Request.Path" asp-controller="Shop" asp-action="ProductDetail"><i class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                </div>
                            </td>
                            <td class="align-middle">₽ @item.Product.Price</td>
                            <td class="align-middle"><a asp-action="RemoveProductFromFeatur" asp-controller="Shop" asp-route-id="@item.Id" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

AnimeShop/Views/Shop/ProductDetail.cshtml
@{
    ViewData["Title"] = "Detail";
}
@model ProductViewModel


<div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="@Model.ReturnUrl">Shop</a>
                    <span class="breadcrumb-item active">Shop Detail</span>
                </nav>
            </div>
        </div>
    </div>
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="@Model.Product.ImageURl" alt="Image">
                        </div>
                        </div>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>@Model.Product.Title</h3>
                    <h3 class="font-weight-semi-bold mb-4">$ @Model.Product.Price</h3>
                    <div class="d-flex align-items-center mb-4 pt-2">
                    <form asp-action="AddToCart" asp-controller="Shop" asp-route-returnURL="@Context.Request.Path" asp-route-id="@Model.Product.Id" class="d-flex align-items-center mb-4 pt-2">
                        <div class="input-group quantity mr-3" style="width: 130px;">
                            <div class="input-group-btn">
                                <a class="btn btn-primary btn-minus">
                                    <i class="fa fa-minus"></i>
                                </a>
                            </div>
                            <input readonly name="amount" type="text" class="form-control bg-secondary border-0 text-center" value="1">
                            <div class="input-group-btn">
                                <a class="btn btn-primary btn-plus">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary px-3">
                            <i class="fa fa-shopping-cart mr-1"></i> Add To Cart
                        </button>
                    </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Description</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Product Description</h4>
                            <p>@Model.Product.Description</p>
                            <h5>Category:</h5>
                            <p>@Model.Product.Category.Title</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

AnimeShop/Views/Shop/ShopCart.cshtml
@{
    ViewData["Title"] = "Shopping cart";
}
@model Order
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" asp-action="Index" asp-controller="Home">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th></th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    @foreach (var item in Model.OrderProducts)
                    {
                        <tr>
                            <td class="align-middle">@item.Product.Title</td>
                            <td> <div class="product-item">
                                    <div class="product-img position-relative overflow-hidden">
                                        <img class="img-fluid w-100" src="@item.Product.ImageURl" alt="">
                                        <div class="product-action">
                                            <a class="btn btn-outline-dark btn-square" asp-route-returnURL="@Context.Request.Path" asp-route-id="@item.Product.Id" asp-controller="Shop" asp-action="AddToFavourites"><i class="far fa-heart"></i></a>
                                            <a class="btn btn-outline-dark btn-square" asp-route-id="@item.Product.Id" asp-route-returnURL="@Context.Request.Path" asp-controller="Shop" asp-action="ProductDetail"><i class="fa fa-search"></i></a>
                                        </div>
                                    </div>
                            </div></td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <a asp-action="RemoveCountProduct" asp-controller="Shop" asp-route-returnURL="@Context.Request.Path" asp-route-id="@item.ProductId" class="btn btn-sm btn-primary btn-minus">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                    </div>
                                    <input type="text" readonly class="form-control form-control-sm bg-secondary border-0 text-center" value="@item.Amount">
                                    <div class="input-group-btn">
                                        <a asp-action="AddCountProduct" asp-controller="Shop" asp-route-returnURL="@Context.Request.Path" asp-route-id="@item.ProductId" class="btn btn-sm btn-primary btn-plus">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">@item.TotalPrice</td>
                            <td class="align-middle"><a asp-action="RemoveProduct"  asp-controller="Shop"  asp-route-id="@item.ProductId" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>₽ @Model.totalPrice</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">₽0</h6>
                    </div>
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5> ₽ @Model.totalPrice</h5>
                    </div>
                    <a asp-action="CheckOut" asp-controller="Shop" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>

AnimeShop/Views/Shop/ShopList.cshtml
@{
    ViewData["Title"] = "Shop List";
}

@model ShopViewModel


<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    @foreach (var item in Model.Categories)
                    {
                        <a asp-action="ShopList" asp-controller="Shop" asp-route-CategoryId="@item.Id" class="nav-item nav-link">@item.Title</a>
                    }

                </div>
            </nav>

        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase px-2">DWC shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a asp-action="Index" asp-controller="Home" class="nav-item nav-link">Home</a>
                        <a asp-action="ShopList" asp-controller="Shop" class="nav-item nav-link active">Shop</a>
                        @if (Model.User != null && Model.User.TypeOfAcc == "Admin")
                        {
                            <a asp-area="Admin" asp-controller="Start" asp-action="Start" class="nav-item nav-link">Admin panel</a>

                        }
                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        <a asp-action="Favourites" asp-controller="Shop" class="btn px-0">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">@ShopViewModel.CountItemFacourites</span>
                        </a>
                        <a asp-action="ShopCart" asp-controller="Shop" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">@ShopViewModel.CountItemCart</span>
                        </a>

                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" asp-action="Index" asp-controller="Home">Shop</a>
                <span class="breadcrumb-item active">Shop List</span>
            </nav>
        </div>
    </div>
</div>
<div class="container-fluid">
    <form asp-action="ShopList" asp-controller="Shop" method="get">
        <input asp-for="SearchTitle" type="hidden" />
        <div class="row px-xl-5">
            <div style="z-index:999" class="col-lg-3 col-md-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span></h5>
                <div class="bg-light p-4 mb-30">

                    <div class="wrapper">
                        <header>
                            <h2>Price Range</h2>
                            <p>Use slider or enter min and max price</p>
                        </header>
                        <div class="price-input">
                            <div class="field">
                                <span>Min</span>
                                <input name="minPrice" type="number" class="input-min" value="@Model.minPriceProd">
                            </div>
                            <div class="separator">-</div>
                            <div class="field">
                                <span>Max</span>
                                <input name="maxPrice" type="number" class="input-max" value="@Model.maxPriceProd">
                            </div>
                        </div>
                        <div class="slider">
                            <div class="progress"></div>
                        </div>
                        <div class="range-input">
                            <input type="range" class="range-min" min="0" max="@Model.maxPrice" value="@Model.minPriceProd" step="10">
                            <input type="range" class="range-max" min="0" max="@Model.maxPrice" value="@Model.maxPriceProd" step="10">
                        </div>
                    </div>
                </div>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by category</span></h5>
                <div class="bg-light p-4 mb-30">
                    <select name="CategoryId" class="form-select" aria-label="Select Category">
                        <option selected value="">Selected category</option>
                        @foreach (var item in Model.Categories)
                        {
                            @if (@item.Id == Model.CategoryID)
                            {

                                <option selected value="@item.Id">@item.Title</option>
                            }
                            else
                            {
                                <option value="@item.Id">@item.Title</option>
                            }
                        }
                    </select>
                </div>
                <button class="btn btn-primary px-3" type="submit"><i class="fa fa-shopping-cart mr-1"></i> Search</button>

            </div>
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                        </div>
                    </div>

                    @if (Model.Products.Count != 0)
                    {

                        @foreach (var item in Model.Products)
                        {
                            <partial name="_ProductItemPartial" model="@item"></partial>
                        }
                    }
                    else
                    {
                        <h2 class="text-center">Clear your filter</h2>
                    }

                </div>

            </div>
    </form>

</div>
</div>